--- 
final_name: sample
min_cli_version: 0.15.2
blobstore: 
  provider: atmos
  options: 
    tag: BOSH
    url: https://blob.cfblob.com
    uid: 0559221ba3f64d73a60dced2912c9e6b/user1
blobstore_options: deprecated
