---
name: wordpress-openstack
director_uuid: <director_uuid> # CHANGE

release:
  name: wordpress
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: <flavor_name> # CHANGE

update:
  canaries: 1
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  max_in_flight: 4

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: default
    type: manual
    subnets:
      - name: private
        range: <subnet_cidr> # CHANGE
        gateway: <subnet_gateway> # CHANGE
        reserved:
          - <first_reserved_ip_address> - <last_reserved_ip_address> # CHANGE
        static:
          - <first_ip_address_for_vms> - <last_ip_address_for_vms> # CHANGE
        cloud_properties:
          security_groups:
            - default
            - <microbosh_security_group> # CHANGE
            - <wordpress_security_group> # CHANGE
          net_id: <network_uuid> # CHANGE

resource_pools:
  - name: common
    network: default
    size: 4
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: <flavor_name> # CHANGE

jobs:
  - name: mysql
    template: mysql
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_mysql> # CHANGE

  - name: nfs
    template: debian_nfs_server
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_nfs> # CHANGE

  - name: wordpress
    template: wordpress
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_wordpress> # CHANGE

  - name: nginx
    template: nginx
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - <ip_address_for_nginx> # CHANGE
      - name: floating
        static_ips:
          - <allocated_floating_ip> # CHANGE

properties:
  mysql:
    address: <ip_address_for_mysql> # CHANGE
    password: c1oudc0w

  nfs_server:
    address: <ip_address_for_nfs> # CHANGE
    network: <subnet_cidr> # CHANGE

  wordpress:
    admin: foo@bar.com
    servers:
      - <ip_address_for_wordpress> # CHANGE
    servername: <allocated_floating_ip> # CHANGE
    db:
      name: wp
      user: wordpress
      pass: c1oudc0w
    auth_key: random key
    secure_auth_key: random key
    logged_in_key: random key
    nonce_key: random key
    auth_salt: random key
    secure_auth_salt: random key
    logged_in_salt: random key
    nonce_salt: random key