---
name: wordpress-openstack
director_uuid: <director_uuid> # CHANGE

release:
  name: wordpress
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: <flavor_name> # CHANGE

update:
  canaries: 1
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
        - default
        - <microbosh_security_group> # CHANGE
        - <wordpress_security_group> # CHANGE

resource_pools:
  - name: common
    network: default
    size: 4
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: <flavor_name> # CHANGE

jobs:
  - name: mysql
    template: mysql
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

  - name: nfs
    template: debian_nfs_server
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

  - name: wordpress
    template: wordpress
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]

  - name: nginx
    template: nginx
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
          - <allocated_floating_ip> # CHANGE

properties:
  mysql:
    address: 0.mysql.default.wordpress-openstack.microbosh
    password: c1oudc0w

  nfs_server:
    address: 0.nfs.default.wordpress-openstack.microbosh
    network: "*.wordpress-openstack.microbosh"

  wordpress:
    admin: foo@bar.com
    servers:
      - 0.wordpress.default.wordpress-openstack.microbosh
    servername: <allocated_floating_ip> # CHANGE
    db:
      name: wp
      user: wordpress
      pass: c1oudc0w
    auth_key: random key
    secure_auth_key: random key
    logged_in_key: random key
    nonce_key: random key
    auth_salt: random key
    secure_auth_salt: random key
    logged_in_salt: random key
    nonce_salt: random key